language: go

go:
- 1.5
- 1.6
- 1.7
- tip

matrix:
  allow_failures:
  - go: tip

before_install:
  - go get github.com/mattn/goveralls
before_script:
  - go get -d ./...
script:
  - go test -v ./... -bench=.
 - $HOME/gopath/bin/goveralls -service=travis-ci
